#!/bin/python

import re

#data = ["Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green", "Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue", "Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red", "Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red", "Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green"]

data = []
with open("H:\Tasks\Coding\Python\work\ssh\AOC\Day2\data.txt", 'r') as importfile:
    importfile.seek(0)
    for line in importfile.readlines():
        data.append(line.rstrip("\n"))
importfile.close()

id_list = []
for id, game in enumerate(data):
    id_list.append(id + 1)

temp = []
for id, game in enumerate(data):
    ## print out each lines
    for item in game.split(":")[1].split(";"):
        for sub_item in item.split(","):
            number = sub_item.strip().split(" ")[0].strip()
            color = sub_item.strip().split(" ")[1].strip()
            if (int(number) > 12 and color == "red") or (int(number) > 13 and color == "green") or (int(number) > 14 and color == "blue"):
                print(id + 1)
                if (id + 1) not in temp:
                    temp.append(id + 1)

for i in temp:
    if i in id_list:
        id_list.remove(i)

print(id_list)
print (sum(id_list))
